### ISSUE TITLE
Problem with sectors when compiling world second time

### ISSUE THREAD

**Issue by SaiyansKing** [postm1/SpacerNET_Union#16]
There is a problem with engine function "zCCBspTree::CreateBspSectors" that breaks the sectors when there are cached materials from previous world compilation. Because those materials are already loaded engine can't assign new bsp sectors to them and they will remain with dangling pointers.

Proposed fix: unload all sector materials when loading a new mesh(they start with prefix "S:").

Temporary fix: patch file that allows to assign new bsp sectors to previously loaded sector materials
[Fix_CreateBspSectors.patch](https://github.com/user-attachments/files/16274526/Fix_CreateBspSectors.patch)

**Comment by Patrix9999** [comment]
Hi, thanks for providing the details about the bug.  
I personally managed to only pin point that materials are causing this problem, i didn't found the exact location of the problem.

https://github.com/postm1/SpacerNET_Union/pull/17
Here's the pull request with a fix, i hope that it gets merged ASAP.

**Comment by postm1** [comment]
Closed, solved

**Comment by Patrix9999** [comment]
There was an issue with removing materials, that were using `S:` prefix, because the game itself might load some of them due to the feature that allows you to override their properties via .pml files.

We've changed the fix to your mem patch.
