### ISSUE TITLE
Left Alt key freezes the program

### ISSUE THREAD

**Issue by postm1** [postm1/SpacerNET_Union#7]
When you press LEFT ALT, spacer freezes for ~ 0.5 second, that bug appears in game mode (contol hero) or when you set keys in keybinding interface.
Why? No idea, if someone can help with it.

**Comment by bogu9821** [comment]
I see that LEFT ALT checks the "File" option on the menu bar and in game mode it is disabled to manipulate and it still can check it.
RIGHT ALT works fine with no lag and the player can jump correctly, so it's probably something to do with the UI/spacebar binding.

![obraz](https://github.com/postm1/SpacerNET_Union/assets/30447446/4cf15918-8290-4ca5-870f-d386dc513362)

**Comment by postm1** [comment]
Yeah, interestring, may be to skip it somehow in interfaces keys. Thanks.

**Comment by postm1** [comment]
Yeah, it works, just check this key in C# interface, will fix it, thanks ;)
